### ISSUE TITLE
Error: Task do_populate_sdk in .... rdepends upon non-existent task do_package_write_deb

### ISSUE THREAD

**Issue by MehdiJaiem502** [bdx-iot/meta-stm32mp1#52]
Hello

I am trying to build an Image based on the Yocto Project for my stm32mp157c-DK2 according to :
https://wiki.st.com/stm32mpu/wiki/STM32MP1_Distribution_Package#Building_the_OpenSTLinux_distribution

When I try to build the image I get the following error.
`ERROR: Task do_populate_sdk in /home/mehdi/Distribution-Package/openstlinux-5.4-dunfell-mp1-20-11-12/layers/meta-st/meta-st-openstlinux/recipes-st/images/st-image-weston.bb rdepends upon non-existent task do_package_write_deb in /home/mehdi/Distribution-Package/openstlinux-5.4-dunfell-mp1-20-11-12/layers/meta-st/meta-st-openstlinux/recipes-st/images/st-image-weston.bb ERROR: Command execution failed: 1`

What did I miss or what did I do wrong in my local.conf file ?

Best regards.

I can share with you the content of the file.

[local.conf.txt](https://github.com/bdx-iot/meta-stm32mp1/files/5673923/local.conf.txt)

**Comment by jorisoffouga** [comment]
Hi @MehdiJaiem502 

You have the wrong repo, it's not meta-st-openlinux : https://github.com/STMicroelectronics/meta-st-openstlinux

Best Regards
